karma.conf.js, src/model/BooleansColumn.ts, src/model/DateColumn.ts, src/model/DatesColumn.ts, src/model/ICategoricalColumn.ts, src/model/SetColumn.ts, src/model/StringColumn.ts, src/model/missing.ts
fixes inconsistencies whether missing values are the biggest value (string, categorical) or the smallest one (number)
=> Missing string order

src/ui/dialogs/MappingsFilterDialog.ts
closes <list issues here>
fix diverse bugs for the mapping editor
=> Mapping editor

README.md
=> Updated datavisyn to lineupjs organization

src/model/BooleanColumn.ts, src/model/BoxPlotColumn.ts, src/model/CategoricalColumn.ts, src/model/Column.ts, src/model/CompositeColumn.ts, src/model/DateColumn.ts, src/model/DatesColumn.ts, src/model/DatesMapColumn.ts, src/model/INumberColumn.ts, src/model/ImpositionBoxPlotColumn.ts, src/model/ImpositionCompositeColumn.ts, src/model/ImpositionCompositesColumn.ts, src/model/LinkColumn.ts, src/model/NumberColumn.ts, src/model/NumberMapColumn.ts, src/model/NumbersColumn.ts, src/model/OrdinalColumn.ts, src/model/Ranking.ts, src/model/ScriptColumn.ts, src/model/SetColumn.ts, src/model/StringColumn.ts, src/provider/ADataProvider.ts, src/provider/interfaces.ts, src/styles/panel/_index.scss, src/ui/dialogs/DateFilterDialog.ts, src/ui/panel/SidePanel.ts
=> implement reset all button

src/renderer/StringCellRenderer.ts, src/ui/dialogs/SearchDialog.ts, src/ui/dialogs/StringFilterDialog.ts, src/ui/dialogs/groupString.ts
=> Rename "RegExp" into "Use regular expressions" (LineUp v4)

src/renderer/StringCellRenderer.ts, src/ui/dialogs/SearchDialog.ts, src/ui/dialogs/StringFilterDialog.ts, src/ui/dialogs/groupString.ts
=> Rename "RegExp" into "Use regular expressions" (LineUp v3.1.8)

package-lock.json, package.json
For release notes see https://github.com/lineupjs/lineupjs/pull/177
=> Update version number for release v3.2.0

src/styles/renderer/_bar.scss, src/styles/renderer/_rank.scss
closes #172 
set the font-variant-numeric as suggested
=> Use font-variant-numeric

src/model/StringColumn.ts, src/ui/dialogs/StringFilterDialog.ts
closes lineupjs/lineupjs#197
Before:
After:
=> Regular expression based text filter bug

README.md
closes #242 
add link for the observablehq wrapper, see also https://lineup.js.org/integrations/observablehq
=> add observable link

src/renderer/AggregateGroupRenderer.ts
closes #217
fix missing clearing of the cell in case there is no grouping
=> Clear aggregation and update group column accordingly

src/internal/utils.ts, src/renderer/ANumbersCellRenderer.ts, src/renderer/HeatmapCellRenderer.ts, src/renderer/VerticalBarCellRenderer.ts, src/ui/dialogs/utils.ts
=> Add aggregation method hint to tooltip

src/renderer/HistogramCellRenderer.ts, src/renderer/histogram.ts, src/styles/_vars.scss, src/styles/renderer/_histogram.scss
closes #190
applies the number formatter to the interactive histogram
=> Use number format of column in interactive summary

src/model/LinkColumn.ts, src/model/StringColumn.ts, src/renderer/StringCellRenderer.ts, src/ui/dialogs/StringFilterDialog.ts
closes #237
note: API change, the `StringColumn.setFilter` method has a changed API. The existing dumps are backward compatible.
=> String column: Filter independently for missing values and text input

src/model/StringColumn.ts, src/ui/toolbar.ts
=> Add missing Sort Group By for StringColumn

src/ui/dialogs/GroupDialog.ts, src/ui/dialogs/SortDialog.ts
=> Fix reset of group and sort dialog

.github/ISSUE_TEMPLATE/bug.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/ISSUE_TEMPLATE/question.md, .github/PULL_REQUEST_TEMPLATE.md, package.json
closes #202
update the browser list along with the PR template to reflect it. Moreover, I added a bunch of issue templates for better issue management
=> Update browserlist and issue templates

.circleci/config.yml, .gitpod.yml, README.md
closes #300 based on #298 
This commit adds support for Gitpod.io, a free automated dev environment that makes contributing and generally working on GitHub projects much easier. It allows anyone to start a ready-to-code dev environment for any branch, issue and pull request with a single click.
We can also add this config to the https://github.com/lineupjs/lineup_app repository, so that one can edit the app as well.
=> Add gitpod config

cypress/integration/pr292_data_mapping.spec.ts, src/styles/_dialogs.scss, src/styles/_mappingeditor.scss, src/styles/_vars.scss, src/styles/engine/_index.scss, src/ui/dialogs/MappingDialog.ts, src/ui/dialogs/MappingLineDialog.ts
based on #289 for cypress utils
closes #285, #286 
=> Improve data mapping dialog

README.md
* Update releated publications in README.md
=> Update releated publications in README.md

demo/missing.html, src/renderer/LinkCellRenderer.ts, src/styles/renderer/_string.scss
=> Fix missing values and overflow of aggregated groups in link renderer 

src/provider/LocalDataProvider.ts
=> Fix sort group optimization

package-lock.json, package.json
I need to upgrade the Cypress dependency to the latest version 4.5.0 due to some CircleCI build error in our customer build.
=> Update Cypress dependency to 4.5.0

cypress/integration/issue-322_group-boxplot-missing-values.spec.ts, src/renderer/AAggregatedGroupRenderer.ts, src/renderer/BoxplotCellRenderer.ts, src/renderer/CategoricalCellRenderer.ts, src/renderer/CategoricalHeatmapCellRenderer.ts, src/renderer/CategoricalStackedDistributionlCellRenderer.ts, src/renderer/DateCellRenderer.ts, src/renderer/DateHistogramCellRenderer.ts, src/renderer/DotCellRenderer.ts, src/renderer/HeatmapCellRenderer.ts, src/renderer/HistogramCellRenderer.ts, src/renderer/LinkCellRenderer.ts, src/renderer/LinkMapCellRenderer.ts, src/renderer/SetCellRenderer.ts, src/renderer/SparklineCellRenderer.ts, src/renderer/StringCellRenderer.ts, src/renderer/utils.ts
closes #322
proper detect missing groups
=> missing group values

src/renderer/DefaultCellRenderer.ts
closes #320 
set title attribute in default renderer
=> Add tooltip for strings column

cypress/integration/utils/ui.ts, src/ui/dialogs/ADialog.ts, src/ui/dialogs/DialogManager.ts, src/ui/dialogs/MoreColumnOptionsDialog.ts, src/ui/dialogs/MoreRankingOptionsDialog.ts
closes #326
auto closes menu dialogs (more options, more ranking options)
=> Auto close menu dialogs

demo/frozen.html, src/styles/engine/_header.scss, src/styles/engine/_row.scss
=> Fix frozen column shift

README.md
=> Fix typo in LineUp htmlwidget

src/model/ICategoricalColumn.ts, src/model/SetColumn.ts, src/model/internalCategorical.ts, src/renderer/CategoricalCellRenderer.ts, src/ui/dialogs/CategoricalFilterDialog.ts
=> Filter all or some categories in `SetColumn`

src/renderer/MultiLevelCellRenderer.ts
=> Fix overlapping numbers for stacked bar renderer v3

src/styles/renderer/_rank.scss
=> Vertically canter rank number with increased height

src/model/StringColumn.ts, src/ui/dialogs/StringFilterDialog.ts, src/ui/dialogs/groupString.ts
Closes  #350
re `Venezuela RB` it contains a capital B thus is correct match. in order to only limit to the first character it would require `^B` as a regex
=> Improve group by for string column

cypress/integration/utils/ui.ts, package-lock.json, package.json
=> Add tslib as dependency

src/model/internalCategorical.ts
Closes #359
fix filter comparison issue
=> Fix categorical filter comparison

cypress/integration/restore_ranking.spec.ts, src/model/Column.ts, src/model/StringColumn.ts
Closes #355
fixes dumping and loading lineup state by fixing missing column ids
=> restore grouping aggregations

src/styles/renderer/_rank.scss
=> Fix centering of rank

src/renderer/GroupCellRenderer.ts, src/styles/renderer/_aggregate.scss, src/styles/renderer/_string.scss, src/ui/EngineRanking.ts
=> Fix group clipping

demo/group.html, src/provider/ADataProvider.ts
=> Disable unify/merge groups if group sorting is present

src/provider/ACommonDataProvider.ts, src/provider/ADataProvider.ts
=> Add `ACommonDataProvider.removeDesc()`

.circleci/config.yml
Closes #366 
TODO needs to be tested in develop or master branch
=> Copy LineUp build files to auto update the app

src/styles/taggle/_switcher.scss, src/ui/taggle/Taggle.ts, src/ui/taggle/TaggleRenderer.ts, src/ui/taggle/rules.ts
=> Fix Taggle overview warning

cypress/integration/issue373_auto_enlarge_aggregation.spec.ts, src/model/AggregateGroupColumn.ts, src/model/Ranking.ts, src/styles/index.ts
Closes #373
auto increases the width of the aggregation column based on the number of grouping criteria.
=> Increase width of aggregation column automatically based on the number of grouping criteria

demo/small_numbers.html, package-lock.json, package.json, src/model/INumberColumn.ts, src/model/NumberColumn.ts, src/model/internalNumber.ts, src/provider/utils.ts
* Merge pull request #400 from lineupjs/thinkh/399_fix-empty-array-in-dataset (174b8e45)
* Fix `[]` and `null` values for dataset properties (07fef7bb)
* Merge pull request #396 from lineupjs/thinkh/customizable-filter-accuracy (668f6e8b)
* Add filter accuracy to `INumberDesc` (1ac0955c)
* Prepare next dev branch (25cc8b77)
* Merge pull request #392 from lineupjs/release-4.1.1 (4a97202b)
=> Release 4.1.2

demo/frozen.html, package.json, src/styles/_vars.scss, src/ui/RenderColumn.ts, yarn.lock
Closes #420 
fixes the frozen shift error but updating to lineupengine 2.3.0
=> fix frozen shift error

src/internal/utils.ts, src/model/CategoricalColumn.ts, src/model/internalCategorical.ts
Even tho there are no circular dependencies in LineUp anymore CodeSandbox still complains in this matter. This might fix it. 
https://codesandbox.io/s/brave-mclaren-09s15?file=/src/index.js is a code sandbox where I copied all the compiled sources of LineUp in. This one works. But we need to release the library in order to really try it out
=> possible fixes for codesandbox

src/styles/panel/_search.scss, src/ui/panel/Hierarchy.ts, src/ui/panel/SearchBox.ts, src/ui/panel/SidePanel.ts
closes #408
add the summary/description to the column adder, sort/group hierarchy adder:
=> feat: add summary to column adder

src/renderer/CategoricalCellRenderer.ts, src/renderer/DotCellRenderer.ts, src/renderer/SparklineCellRenderer.ts, src/renderer/UpSetCellRenderer.ts, src/styles/_vars.scss, src/styles/renderer/_dot.scss, src/styles/renderer/_sparkline.scss
closes #471, closes #466, closes #463, closes #458
re #471
=> optimize visualizations

src/model/SelectionColumn.ts, src/styles/renderer/_selection.scss
=> Improve Selection Column

demo/violin.html, src/internal/math.ts, src/internal/mathInterfaces.ts, src/renderer/ViolinPlotCellRenderer.ts, src/renderer/rendererClasses.ts, src/renderer/renderers.ts, src/styles/renderer/_index.scss, src/styles/renderer/_violin.scss
closes #494 
creates a basic violin chart renderer
=> Violin Chart

demo/htmlLabel.html, src/builder/column/ColumnBuilder.ts, src/internal/dnd.ts, src/model/Column.ts, src/model/CompositeColumn.ts, src/model/Ranking.ts, src/model/interfaces.ts, src/styles/engine/_header.scss, src/styles/header/_index.scss, src/ui/dialogs/ADialog.ts, src/ui/dialogs/MappingDialog.ts, src/ui/dialogs/RenameDialog.ts, src/ui/header.ts, src/ui/panel/Hierarchy.ts, src/ui/panel/SidePanel.ts, src/ui/panel/SidePanelEntryVis.ts
closes #540
see flags in column desc and `htmlLabel.html` example
=> Add option for html labels and summaries

demo/taggle_nopanel.html, src/ui/taggle/Taggle.ts, src/ui/taggle/TaggleRenderer.ts
closes #551
refactor overview mode toggle to be set via `setOverviewMode`. In addition, allow to disable the side panel within Taggle
=> Taggle overview mode

src/renderer/SetCellRenderer.ts
Closes #559
* Correct update of color mapping for the matrix renderer
=> Fix color mapping update for matrix renderer

src/ui/EngineRanking.ts
closes #564 
similar to #560 but for frozen columns which weren't considered.
=> Also apply frozen offset

cypress/integration/custom_instance_id.spec.ts, src/builder/LineUpBuilder.ts, src/config.ts, src/ui/EngineRenderer.ts, src/ui/dialogs/CompositeChildrenDialog.ts
* By default LineUp is generating a random id with 3 characters (e.g. `luc75`)
* This PR allows to set a deterministic id for this LineUp instance in the options (i.e., `options.instanceId`)
* If no `instanceId` is set or by default the id is generated as before
=> Add option for custom instance id

src/internal/scheduler.ts, src/model/SelectionColumn.ts
closes https://github.com/lineupjs/lineupjs/issues/554, closes #570 
=> Allow removal of selection columns from ranking + fix error in scheduler.ts

src/styles/renderer/_string.scss
=> fix: text filter no wrap and overflow

src/renderer/DateHistogramCellRenderer.ts, src/renderer/HistogramCellRenderer.ts, src/renderer/histogram.ts
=> fix: don't cross histogram filter

src/model/Column.ts, src/styles/_vars.scss, src/styles/engine/_header.scss, src/styles/engine/_row.scss, src/styles/header/_toolbar.scss, src/styles/index.ts, src/styles/panel/_index.scss
closes #574 
BREAKING UX CHANGE
=>  use background selection indicator

README.md, package.json, src/builder/column/StringColumnBuilder.ts, src/builder/column/index.ts, src/index.ts, src/model/LinkColumn.ts, src/model/Ranking.ts, src/model/ScriptColumn.ts, src/model/index.ts, src/provider/index.ts, src/ui/dialogs/index.ts, src/ui/index.ts, src/ui/taggle/TaggleRenderer.ts, src/ui/taggle/index.ts, tsconfig.dev.json, yarn.lock
closes #593 
fix docs links and fixes all missing exports
=> fix doc links and fix exports

demo/number_min_rep.html, src/model/INumberColumn.ts, src/renderer/BarCellRenderer.ts
=> feat: add support for 1px min bar

demo/bool.html, src/builder/column/BooleanColumnBuilder.ts, src/model/BooleanColumn.ts
=> feat: advanced boolean parsing

src/builder/DataBuilder.ts
closes #630
implement patch as suggested
=> feat: change key for detecting duplicates

src/styles/_dialogs.scss, src/ui/dialogs/SearchDialog.ts
Closes #656 
- Add previous and next button
- Show count indicator when search term is entered
- Remove minimum character limit
- When the search input has the focus, you can jump to the next result by pressing the Enter key
[lineup-search-dialog.webm](https://github.com/lineupjs/lineupjs/assets/5851088/e814abfc-0e14-4283-baba-b248613379a2)
Note that I hit the Enter key when I searched for "er" in the video.
=> feat: improve string column search dialog

package.json, src/styles/_dialogs.scss, src/styles/header/_toolbar.scss, src/ui/dialogs/ADialog.ts, src/ui/headerTooltip.ts, yarn.lock
Closes #664 
- deps: migrate from popper to the successor library [floating-ui](https://floating-ui.com/) 
- feat: dynamic dialog placement and overflow on max-height
- feat: highlight active more menu item
[lineup-fix-menu-outside-viewport.webm](https://github.com/lineupjs/lineupjs/assets/5851088/62ba51f2-ae23-4f3b-a31b-e1ee8d6ed8fc)
=> fix(dialogs): dynamic dialog placement and scrollbars on max-height

src/builder/LineUpBuilder.ts
closes 
- Expose config options introduced/used by https://github.com/lineupjs/lineupjs/pull/674 to LineUpBuilder
=> feat: expose config options to `LineUpBuilder`
