lineupjs/lineupjs

package.json
Coming from https://github.com/datavisyn/lineupjs/pull/20
Related to https://github.com/datavisyn/lineup_app/issues/15
Adding the `prepare` script allows to install this repo from git URI:
```
npm install --save git+https://github.com/datavisyn/lineupjs.git
```
Or for instance by modifying the dependency in the `package.json` of [lineup_app](https://github.com/datavisyn/lineup_app/): 
```
"dependencies": {
"lineupjs": "github:Caleydo/lineupjs#develop",
}
```
For further information see:
* https://docs.npmjs.com/misc/scripts
* https://github.com/npm/npm/issues/3055
* Example: https://github.com/tasti/react-linkify/pull/61
**NOTE!**
Using the git URI as dependency will build the LineUp library on `npm install`. Then the whole install process will take longer than usual. …
=> Replace npm script `prepublishOnly` with `prepare`

src/styles/renderer/_histogram.scss
Reduce the gap between two bars from (in total) 2px to 1px.
Background: With `display:flex` the collapsing margin should already result in 1px gap, but it does not work.
**Column summary before**
**Column summary after**
**Sidepanel before**
**Sidepanel after**
=> Decrease margin of histograms

src/model/DateColumn.ts
Related to https://github.com/datavisyn/tdp_core/issues/138#issuecomment-441655271
This change sets the return value of `DateColumn.compare()` to avoid the `import()` statement in the `DateColumn.d.ts` file.
The use of import statements in return values is incompatible with TS 2.7.2.
=> Explitly set return type of DateColumn.compare()

src/model/MappingFunction.ts, src/model/interfaces.ts
Related issue https://github.com/datavisyn/tdp_core/issues/138#issuecomment-441655310
The functions `isGroup()` and `createMappingFunction()` are exported, but ignored in the *.d.ts files. Removing the `internal` comment should fix this and make it available for the integration in tdp_core.
=> Expose `isGroup()` and `createMappingFunction()` in *.d.ts files

src/renderer/CategoricalStackedDistributionlCellRenderer.ts
closes https://github.com/datavisyn/tdp_core/issues/144
Debugging https://github.com/datavisyn/tdp_core/issues/144 revealed that the missing value div is rendered two times:
The first one is added right after mapping the categories:
https://github.com/datavisyn/lineupjs/blob/c0a9ba907f6cb1cd64024958453331a206314c33/src/renderer/CategoricalStackedDistributionlCellRenderer.ts#L91
The other one is introduced in the renderer template.
The duplication leads to a problem, as the renderer iterates over the DOM collection and there are less categories available.
https://github.com/datavisyn/lineupjs/blob/c0a9ba907f6cb1cd64024958453331a206314c33/src/renderer/CategoricalStackedDistributionlCellRenderer.ts#L98-L103
I removed the last div from the renderer template and now the …
=> Fix label for missing values in  `CategoricalStackedDistributionlCellRenderer`

demo/nested_bug_pr133.html, src/renderer/AAggregatedGroupRenderer.ts, src/renderer/MultiLevelCellRenderer.ts, src/styles/renderer/_stack.scss
closes Caleydo/lineup_app#46
The over-sizing is caused by the increased row height for aggregated groups.
Reducing the row height to the standard `18px` will result in a normal heatmap width for nested columns.
As soon as I increase the height the width of the nested heatmaps increases exceeds the column.
By adding a `width:100%` the heatmaps stay within their column width.
However, now the gap between the nested columns disappeared. Hence, we must subtract the gap from the width to stay inline with the (nested column) grid.
=> Prevent over-sizing of group heatmaps in nested columns

src/styles/_lineup.scss, src/styles/_safari.scss, src/ui/dialogs/DialogManager.ts
closes #143 
uses Safari CSS hacks to remove the translate3d from header and side panel, since it confuses Safari + use prefix clip path for proper backdrop support
=> work on safari translate3d issues

package.json
`npm run prepack` is used if lineupjs is added as git dependency (e.g., in the lineup_app). With the most recent changes, the lineup_app will not compile, due to missing .d.ts files. Generating the typings when installing lineupjs as dependency fixes the problem.
=> Generate `types:27` on `npm run prepack`

src/styles/_lineup.scss
Bootstrap style sheets (tested v3.3.7 and v4.3.1) set the line-height declaration in the body selector to a value higher than the default. This causes rows in LineUp to overflow and trigger many unnecessary scroll events that slow down vertical scrolling. Setting the line-height to the default value in LineUp fixes this issue.
=> Improving compatibility with bootstrap styles

src/model/ColorMappingFunction.ts
Closes #174
*  Allow `color` property in column description but show deprecated warning to mantain backward compatibility
=>  Allow `color` property in column description but show deprecated warning

src/ui/missing.ts
closes #101 
A simple backport of the v4 code is not possible, because the whole stat calcuation has been refactored and uses scheduler and tasks.
This PR fixes it in a way that the checkbox is always enabled if the checkbox is checked. 
The number of rows is set to 0 when the filter is active. In my opinion the number of rows with missing values should remain the same, indepdent of the filter status. 
I digged into the problem and found out that the missing values are checked/counted for currently visible rows.
Example: A ranking with 100 rows and 10 missing values for one column. Filtering the missing values shows the remaining 90 rows. Now the count of missing values is 0, which is correct, but at the same time it disables the checkbox. Hence, two missing values …
=> Fix reset of filter for missing values

src/styles/renderer/_bar.scss, src/styles/renderer/_rank.scss
Closes #172 
This is a back port of PR https://github.com/lineupjs/lineupjs/pull/186.
Set the font-variant-numeric as suggested
=> Use font-variant-numeric

src/model/StringColumn.ts, src/ui/dialogs/StringFilterDialog.ts
closes lineupjs/lineupjs#197
Before:
After:
=> Regular expression based text filter bug

demo/string_grouping.html, src/model/StringColumn.ts, src/ui/dialogs/groupString.ts
closes #192  
This PR adds the possibility of grouping a `StringColumn` by its actual value. It adds the option to the `groupString` dialog extension and adds a new type `EStringGroupCriteriaType` and interface `IStringGroupCriteria` to the column, allowing for more than just two criteria types (`string | RegExp` as before).
=> Group by string value in StringColumn

demo/script_column.html, src/model/ScriptColumn.ts
closes #205
This PR fixes an issue when accessing `col.all` in a `ScriptColumn`, because the column itself was included in the column list causing an infinite loop. 
Added demo `script_column.html` for a demonstration.
=> Fixed circular reference in ScriptColumn

package.json
Smiliar to #182 
Revert major version changes of D3 dependencies in d3-array and d3-scale, as they introduce ES2015 syntax which might break older builds that are using ES5. See #181 (comment) for further information.
=> Revert D3 dependencies for LineUp v4

src/model/index.ts
* Addressing feedback from https://github.com/lineupjs/lineupjs/commit/f7890402257b582f64102cb70033cd88480ff9c8
=> Limit export to `toCategories()` only

src/model/index.ts
closes #221 
The two exports are missing from LineUp#V3 (V4 exports everything by default) but required to set the string grouping criteria in a type-safe way.
=> Export StringGroupCriteria interfaces from StringColumn

demo/string_grouping.html, src/model/LinkColumn.ts, src/model/StringColumn.ts, src/ui/dialogs/groupString.ts
LineUp 4 Port of #193
This PR adds the possibility of grouping a `StringColumn` by its actual value. It adds the option to the `groupString` dialog extension and adds a new type `EStringGroupCriteriaType` and interface `IStringGroupCriteria` to the column, allowing for more than just two criteria types (`string | RegExp` as before).
=> Group by string value in StringColumn (V4)

src/model/LinkColumn.ts, src/model/StringColumn.ts, src/model/index.ts
The LinkColumn propagates the calls to the StringColumn, such that the interfaces had to be updated. And to externally set the grouping of StringColumns, it is required to export the interface used for it.
=> Fixed grouping of LinkColumn and exported required interfaces

src/renderer/StringCellRenderer.ts, src/renderer/utils.ts
closes #223 
Added `title` property to nodes rendered with `StringCellRenderer` to show a tooltip of the text on hover.
=> Set title prop in StringCellRenderer

src/model/CompositeColumn.ts, src/model/Ranking.ts
closes #248
upon removing a filtered column that wasn't influencing the ranking order it wasn't detected as something that actually makes the ranking invalid.
=> Fix removal of filtered column

demo/wide.html, src/ui/EngineRanking.ts
closes #224
before:
after:
the issue was the the canvas rendering logic didn't consider the optimized horizontal rendering logic. Thus, didn't update when a column to the left was not rendered anymore (shift to left) or the width changes (missing content on the right)
=> Fix canvas horizontal shift issue

demo/subtitle_summary.html, src/builder/column/ColumnBuilder.ts, src/model/Column.ts, src/model/interfaces.ts, src/styles/engine/_header.scss, src/styles/header/_index.scss, src/styles/panel/_entry.scss, src/ui/EngineRanking.ts, src/ui/MultiLevelRenderColumn.ts, src/ui/RenderColumn.ts, src/ui/dialogs/RenameDialog.ts, src/ui/header.ts, src/ui/panel/SidePanelEntryVis.ts
closes #220 
add a new metadata field to columns `summary` which is rendered below the column label in the table. it can act as a short summary or subtitle of the column.
=> Add subtitle / summary to column headers

src/ui/MultiLevelRenderColumn.ts
closes #258 
fixes the bug that the header of a multilevel column isn't properly updated upon children change.
=> Fix grouping of previously ungrouped column by matching the nested header

src/ui/header.ts
Closes #263
Fixes the undefined element if no sublabel is set.
=> Fix undefined sublabel in `updateHeader()`

src/model/ColorMappingFunction.ts
If both properties `color` and `colorMapping` are set in the column description, LineUp will use the `color` property instead of `colorMapping`. We need to switch the order, so that `colorMapping` has a higher priority and `color` is the backup (as it is deprecated).
=> Switch order of `color` and `colorMapping` in `restoreColorMapping()`

src/model/internal.ts, src/ui/EngineRenderer.ts, src/ui/interfaces.ts, src/ui/toolbar.ts
closes #262
avoid side effects in the module for caching toolbar actions from columns. When developing toolbar addons one could experience caching issues
=> avoid toolbar side effects

src/provider/utils.ts
This commit is a backport of the LineUp v4 functionality. With the current implementation `deriveColors()` is using the deprecated `color` property, which prints a warning message. Switching to `colorMapping` resolves the problem.
=> Remove warning message by using `colorMapping` property in `deriveColors()` 

src/model/internalCategorical.ts
closes #161
unify categorical group sorting similar to value sorting:
=> Sort categorical groups similar to sort values

src/renderer/HistogramCellRenderer.ts, src/ui/dialogs/NumberFilterDialog.ts
closes #282
re renders the number filter histogram in case of the order changed = filter was successfully applied or reset
=> Fix reset of the filter histogram

.circleci/config.yml
Closes #297 
**Prerequisites**: 
Following https://stackoverflow.com/a/58886629
=> Fix CircleCI error by updating the cache key

src/renderer/DateHistogramCellRenderer.ts, src/renderer/HistogramCellRenderer.ts, src/renderer/histogram.ts, src/ui/dialogs/ADialog.ts, src/ui/dialogs/DateFilterDialog.ts, src/ui/dialogs/DialogManager.ts, src/ui/dialogs/MappingDialog.ts, src/ui/dialogs/NumberFilterDialog.ts
=> Optimize filter dialogs

src/internal/drag.ts, src/styles/engine/_header.scss, src/styles/renderer/_histogram.scss
=> Improve dragging of slider

src/renderer/DateHistogramCellRenderer.ts, src/renderer/HistogramCellRenderer.ts, src/renderer/histogram.ts, src/ui/dialogs/ADialog.ts, src/ui/dialogs/DateFilterDialog.ts, src/ui/dialogs/InputDateDialog.ts, src/ui/dialogs/InputNumberDialog.ts
=> Use interactive date summary histogram for filtering

src/renderer/DateHistogramCellRenderer.ts, src/renderer/HistogramCellRenderer.ts, src/ui/EngineRanking.ts, src/ui/panel/SidePanelEntryVis.ts
closes #314
re tdp_core -> `column.markDirty()` should help
=> Renderer update after dirty caches (fix domain in histogram)

demo/dates.html, src/provider/interfaces.ts, src/provider/utils.ts
adds more date patterns date are automatically detected including the most used iso format: 
```js
const f = d3.timeFormat('%x');
for (let i = 0; i < 100; ++i) {
const d = new Date(Date.now() - Math.floor(Math.random() * 1000000000000));
arr.push({
dateObj: d,
dateIso: d.toISOString(),
dateFormatted: f(d),
dateYYYYMMDD: `${d.getFullYear()}-${d.getMonth()+1}-${d.getDate()}`
});
}
```
all 4 formats are now detected as dates
=> add more patterns to detect dates

package-lock.json, package.json
We need to update the node-sass dependency so that the customer build with lineupjs4 is successful again.
Reason the package-lock.json is pointing to node-sass@4.12.0 which does not offer `linux_musl-x64-79_binding.node` bindings to download (see https://github.com/sass/node-sass/releases/tag/v4.12.0). The newest release provides the requested bindings.
=> Update node-sass dependency

src/renderer/StringCellRenderer.ts
Closes datavisyn/tdp_core#374
* Added check in `StringCellRenderer.ts` to convert `{filter:null, filterMissing:False}` to `null `. In other words clear the filter the way we do in `StringFilterDialog`
https://github.com/lineupjs/lineupjs/blob/a3e0b8cd01f41f49c6f1ef991c6497074dc0c462/src/ui/dialogs/StringFilterDialog.ts#L31-L32
Another solution would also be to disable the filterMissing checkbox (as is the case for the categorical and number columns) which would also fix the bug but might require more time implementing.
The result:
=> Clear filter when string column filter is null and filterMissing: false

src/renderer/StringCellRenderer.ts, src/ui/dialogs/SearchDialog.ts, src/ui/dialogs/StringFilterDialog.ts
Prevent different spacings for `Use regular expression` and `Filter missing values`.
**Before**
**After**
=> Add new lines between checkbox and text for equal spacing

src/styles/_common.scss, src/styles/_dialogs.scss
**Before**
**After**
Spacing between checkbox and label is adressed in PR #342.
=> Unify font style + size for checkboxes in dialogs

src/renderer/MultiLevelCellRenderer.ts
Closes #344
Fix scrollbar caused by `overflow-x`
=> Replace `overflow-x` with `overflow` to avoid scrollbars in stacked bars

cypress/integration/utils/ui.ts
fix a race animation condition in a test while aggregating all groups
=> Fix a test race condition

src/provider/ADataProvider.ts, src/renderer/AggregateGroupRenderer.ts
Complements datavisyn/tdp_core#378
When `collapsing/uncollapsing` all groups in the `AggregateGroupColumn` we fire the event 
`ADataProvider.EVENT_GROUP_AGGREGATION_CHANGED` and pass all groups to the callback.
In order to be able to track the aggregation state in `tdp_core` we need to know which groups were `collapsed/expanded` before the event was triggered.
With this PR instead of passing all groups to the event callback, we only pass the groups that have an opposite aggregation state to the one being currently triggered.
=> Minor modification to the AggregateGroupRenderer summary implementation

src/internal/math.ts
Closes #379 
Javascript is weird because `getDay()` does not return what you think it does. See #379 for more information.
=> Changed getDay() to getDate() in date histogram computation

src/model/BooleanColumn.ts
The white for `false` values was not visible and looked like a rendering issue and the black for `true` values had a strong contrast. This commit de-emphasizes the colors.
**Before**
**After**
=> Update colors for boolean values in BooleanColumn

src/model/BooleanColumn.ts
Another minor change to the `False` color and switch the default renderer to the categorical renderer.
**Before**
**After**
=> BooleanColumn: Switch default renderer to categorical renderer

demo/small_numbers.html, src/model/INumberColumn.ts, src/model/NumberColumn.ts, src/model/internalNumber.ts
Related to #188 + #189.
This PR adds a `filterAccuracy` property to `INumberDesc`, which is used as `delta` to compare the row values with the applied filter. This option allows to use smaller delta when using very small numbers (e.g., 1e-9). The default value remains `0.001`.
=> Add `filterAccuracy` property to `INumberDesc`

src/provider/utils.ts
Fixes #399
Previously, deriving the column type was broken for dataset properties containing `[]` or `null`. This fix skips the boxplot and object map detection for `null` values. 
In both cases the column is rendered and the cells contain missing values:
In addition, the console logs the following output:
=> Fix derive column type for dataset properties with `[]` or `null`

src/builder/DataBuilder.ts, src/provider/ADataProvider.ts
closes #403
fixes the bug when the selection column is not added by default
=> add missing selection column

demo/big.html, demo/invert_mapping.html, src/internal/math.ts, src/provider/DirectRenderTasks.ts, src/provider/ScheduledTasks.ts, src/provider/tasks.ts, src/renderer/HistogramCellRenderer.ts
Closes: #397
shows the raw histogram in the interactive side panel:
Thus in the inverted case the visible filter slide matches again the shown histogram. The summary in the column still shows the normalized histogram, since it should match the visible bars.
=> show raw histogram in side panel

tsconfig.json
Fixes #425
Switch `module` setting in tsconfig.json from `esnext` to `es2015`. 
The `esnext` flag is using `ES2020` and [the mentioned syntax](https://github.com/lineupjs/lineupjs/issues/425) since TypeScript 3.8 (see https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#es2020-for-target-and-module). With the dependency update lineupjs switched from Typescript 3.5 to 4.2. Hence, we must explicitly pin `es2015` for now.
=> Switch module to ES2015 in tsconfig.json

tsconfig.json
Closes #423 
Quick fix for tslib compatibility issue: https://github.com/lineupjs/lineupjs/issues/423
Please discuss this approach in the ticket, as setting `importHelpers: false` **IS NOT IDEAL AS IT DEFEATS ITS PURPOSE**, but still better than introducing a breaking change in a minor version. 
Any better solution is appreciated, but we would need a *quick* solution.
=> build: set importHelpers to false for tslib compatibility

src/ui/panel/SearchBox.ts
closes #417
fix the wrongly selected first item + avoided some [deprecated api (`.which`)](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/which)
=> fix: wrong selected initial searchbox item

package.json
the [exports fields](https://webpack.js.org/guides/package-exports/) is quite new and its syntax isn't that stable yet. Moreover, with more tools consider this field, things will fail if the exports field won't include that
=> fix exports field

src/model/StackColumn.ts
Fixes #453
Display missing value for the StackColumn if at least one child value is missing.
**Before**
**After**
The corresponding log output
=> Missing value for StackColumn if at least one child value is missing

src/config.ts
Fixes #457
- Changes the default of the config value `onDialogBackgroundClick` to `confirm`
=> Confirm dialog with click on background

README.md, cypress/integration/utils/data.ts, demo/boxplot.html, src/assets/font/README.md, src/ui/dialogs/DialogManager.ts
to avoid the netlify mixed content error
=> use https links where possible

src/renderer/StringCellRenderer.ts
Fixes https://github.com/lineupjs/lineupjs/issues/522
* Always update label of the datalist option for string column filter
=> Always update label of the datalist option

src/styles/_mappingeditor.scss, src/ui/dialogs/MappingDialog.ts
closes #483
add a static warning:
=> Add mapping dialog warning

src/styles/engine/_selection.scss, src/styles/index.ts, src/ui/EngineRanking.ts, src/ui/EngineRenderer.ts, src/ui/SelectionIndicator.ts
closes #528
add selection indicator on the right
=> selection indicator

src/ui/EngineRenderer.ts
closes #545
re add the missing resize-helper that seems to be deleted by accident when adding the selection indicator
=> Readd deleted resize-helper

demo/manual.html, src/builder/column/NumberColumnBuilder.ts, src/model/MappingFunction.ts, src/model/NumberColumn.ts
closes #544
the builder wasn't support the null variant in detecting whether it should derive some mapping data. Note: the builder derives the mapping based on the data given to the builder. It doesn't propagate the missing mapping domain to the column itself. Since the builder has all the data, this wasn't a use case.
+ added that nulls will be converted to NaN before giving it to d3. This will avoid that the values will be converted to 0.
=> Support null variant in builder and convert null to NaN

src/ui/EngineRanking.ts
Closes #560
* Visualizations are now correctly updated for columns outside of the current viewport
=> Fix switch visualizations outside of the viewport

src/styles/icons/_index.scss
The Font Awesome dependency has been updated from version 5 to version 6 with commit c0d29ff91cb2f147e50ac068617c816a5cbef3e7. However, the font-family has not been updated which results in broken icons. Using the the correct font family name fixes the icons.
Please note that the custom lu-font is still using/set to `Font Awesome 5`.
=> Set `font-family` to Font Awesome 6 when using external FA

src/model/SelectionColumn.ts, src/styles/header/_toolbar.scss, src/styles/panel/_index.scss, src/ui/panel/SidePanel.ts, src/ui/toolbar.ts
closes #501
menu entry:
side panel:
=> feat: add clear button to selection column

demo/htmlLabel.html, src/builder/column/ColumnBuilder.ts, src/model/Column.ts, src/model/interfaces.ts, src/ui/dialogs/MappingDialog.ts, src/ui/header.ts, src/ui/panel/Hierarchy.ts, src/ui/panel/SidePanel.ts, src/ui/panel/SidePanelEntryVis.ts
closes #608
alternative variant from what we have discussed:
the `labelAsHTML` allows either a boolean or a function that is rendering HTML for a given col (desc) in a given context.
=> feat: allow for custom HTML label generation

src/ui/dialogs/CategoricalFilterDialog.ts, src/ui/dialogs/StringFilterDialog.ts
=> feat: filter missing values improvements

src/renderer/BoxplotCellRenderer.ts
Fixes #625
[lineup-fix-boxplot-missing-value.webm](https://github.com/lineupjs/lineupjs/assets/5851088/219c76b0-e5b3-4cf9-abdc-f533ec907218)
=> fix: remove tooltip for missing values of BoxPlotColumn

src/renderer/BoxplotCellRenderer.ts
Reverts lineupjs/lineupjs#626. Because it was accidentally merged into the main branch.
=> Revert "fix: remove tooltip for missing values of BoxPlotColumn"

src/provider/ADataProvider.ts, src/provider/LocalDataProvider.ts, src/provider/RemoteDataProvider.ts, src/provider/interfaces.ts, src/ui/dialogs/SearchDialog.ts
closes #624
adapt search dialog such that you can press enter and it jumps to the next match
=> feat: search next with pressing enter

demo/deriveLink.html, src/provider/utils.ts
closes https://github.com/lineupjs/lineupjs/issues/634
derive a link type if the value starts with http, https, or ftp
=> derive link

src/renderer/SelectionRenderer.ts
closes #679 
[lineup-deselect-all-first.webm](https://github.com/user-attachments/assets/76e9b0ad-adc4-4f52-a6c7-dccb88fae2b4)
=> feat: deselect as default action for selection checkbox

demo/group_sorting.html, src/provider/LocalDataProvider.ts
Fixes #690 
Previously, the `CompareLookup` was initialized with the number of groups (e.g., 15 groups), which initialized an `Uint8Array` that can store numbers up to 255.
https://github.com/lineupjs/lineupjs/blob/c0b4003fda69d563b17f1cd4a9bbf7b60902a1e0/src/internal/math.ts#L754-L762
https://github.com/lineupjs/lineupjs/blob/c0b4003fda69d563b17f1cd4a9bbf7b60902a1e0/src/provider/sort.ts#L36-L37
The problem occurred with groups larger than 255. For example adding a group with 282 rows would only store the value 27 (255 + 27 = 282). This number is then used for the sorting and results in an incorrect sorting. 
The solution is to create an index array with the maximum row length of all groups. Afterwards the groups are sorted in the correct order.
=> fix: group sorting for groups with row length >255 rows

src/styles/renderer/_upset.scss
closes 
* The line is 1px thinner and still centered
* Different approach to center the line
| Before | After |
|--------|--------|
| <img width="441" height="697" alt="image" src="https://github.com/user-attachments/assets/ea462f6a-fcb0-4145-94f4-e3dbc86ee97c" /> | <img width="441" height="697" alt="image" src="https://github.com/user-attachments/assets/307c6206-105f-4296-88f1-aa8e115fa482" /> |
Now, it also works in Ordino with different row height and CSS line height. Before the line was not centered.
| Before | After |
|--------|--------|
| <img width="203" height="382" alt="image" src="https://github.com/user-attachments/assets/09ce9675-d3fa-4b33-8466-0680eeaacc57" /> | <img width="203" height="382" alt="image" …
=> fix: center upset line
